#DATA SCIENCE


#Numpy
is the foundational open-source library for scientific and numerical computing in Python

#Numpy used for
- Numerical computing
- Scientific computing
- Data analysis
- Machine learning
- Artificial Intelligence
- Signal processing
- Matrix operations



The core of NumPy is the ndarray (N-dimensional array), which is much faster and more memory-efficient

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


#Commonly Used NumPy Sub-packages

#numpy.linalg
Linear Algebra operations.

Function used:
- np.linalg.inv()
- np.linalg.det()
- np.linalg.eig()
- np.linalg.solve()
- np.linalg.norm()

In [ ]:
import numpy as np

# Create a matrix A
A = np.array([
    [4, 2],
    [1, 3]
])

# Create vector b for solving equations
b = np.array([10, 8])

print("Matrix A:")
print(A)

print("\nVector b:")
print(b)

In [ ]:
det_A = np.linalg.det(A)
print(det_A)

In [ ]:
inverse_A = np.linalg.inv(A)
print(inverse_A)

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

In [ ]:
solution = np.linalg.solve(A, b)
print(solution)

In [ ]:
norm_A = np.linalg.norm(A)
print(norm_A)

#numpy.random
Random number generation.

Functions Used:
- np.random.rand()
- np.random.randint()
- np.random.randn()
- np.random.choice()
- np.random.shuffle()


In [ ]:
import numpy as np

# For reproducible results
np.random.seed(42)

In [ ]:
import numpy as np

np.random.seed(42)

rand_data = np.random.rand(3, 4)

print(rand_data)

In [1]:
import numpy as np

np.random.seed(42)

student_ages = np.random.randint(
    low=18,
    high=30,
    size=10
)

print(student_ages)

[24 21 28 25 22 24 27 20 24 28]


In [2]:
import numpy as np

np.random.seed(42)

exam_scores = np.random.randn(5)

print(exam_scores)

[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]


In [ ]:
import numpy as np

courses = [
    'Cybersecurity',
    'Data Science',
    'Networking',
    'Software Engineering'
]

selected = np.random.choice(
    courses,
    size=5
)

print(selected)

In [ ]:
import numpy as np

students = np.array([
    'John',
    'Mary',
    'Peter',
    'Alice',
    'David'
])

np.random.shuffle(students)

print(students)

#numpy.fft
commonly used in signal processing, audio analysis, image processing, and communications.


Functions Used:
- np.fft.fft()- Converts a signal from the time domain to the frequency domain.
- np.fft.ifft()- Converts it back from the frequency domain to the time domain.

In [ ]:
import numpy as np

# Original signal
signal = np.array([1, 2, 3, 4])

print("Original Signal:")
print(signal)

# Fast Fourier Transform
fft_result = np.fft.fft(signal)

print("\nFFT Result:")
print(fft_result)

# Inverse FFT
ifft_result = np.fft.ifft(fft_result)

print("\nRecovered Signal:")
print(ifft_result)

In [ ]:
import numpy as np

# Simulated sensor readings
sensor_data = np.array([
    12, 15, 18, 20,
    22, 21, 19, 16
])

fft_data = np.fft.fft(sensor_data)

print("FFT:")
print(fft_data)

restored = np.fft.ifft(fft_data)

print("\nRestored Signal:")
print(restored)

#Array Creation Functions
Functions Used:
- np.array()
- np.zeros()
- np.ones()
- np.empty()
- np.arange()
- np.linspace()
- np.eye()
- np.identity()
- np.full()

In [ ]:
students = np.array([10, 20, 30, 40, 50])

print(students)

In [ ]:
zeros_matrix = np.zeros((3, 4))

print(zeros_matrix)

In [ ]:
ones_matrix = np.ones((2, 5))

print(ones_matrix)

In [ ]:
empty_matrix = np.empty((2, 3))

print(empty_matrix)

In [ ]:
numbers = np.arange(1, 11)

print(numbers)

In [ ]:
even_numbers = np.arange(0, 21, 2)

print(even_numbers)

In [ ]:
line_data = np.linspace(0, 100, 5)

print(line_data)

In [ ]:
eye_matrix = np.eye(4)

print(eye_matrix)

In [ ]:
marks = np.full((3, 4), 50)

print(marks)

#Array Shape Functions
Functions Used:
- arr.shape
- arr.ndim
- arr.size
- arr.dtype

#Reshaping Functions
Functions Used:
- reshape()
- flatten()
- ravel()
- transpose()

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr)

In [ ]:
reshaped = arr.reshape(3, 4)

print(reshaped)

In [ ]:
print(reshaped.shape)

In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

flat = matrix.flatten()

print(flat)

In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

ravel_arr = matrix.ravel()

print(ravel_arr)

In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

transposed = matrix.transpose()

print(transposed)

#Mathematical Functions
Functions Used:
- np.add()
- np.subtract()
- np.multiply()
- np.divide()
- np.power()
- np.sqrt()
- np.exp()
- np.log()
- np.abs()

#Statistical Functions
Function Used:
- np.mean()
- np.median()
- np.mode()  # Not available directly
- np.std()
- np.var()
- np.min()
- np.max()
- np.sum()
- np.percentile()

#Aggregation Functions
Functions Used:
- np.sum()
- np.prod()
- np.cumsum()
- np.cumprod()

#Sorting Functions
Functions Used:
np.sort()
np.argsort()

In [ ]:
arr = np.array([5,3,7,1])

np.sort(arr)

#Searching Functions
Functions Used:
- np.where()
- np.searchsorted()
- np.argmax()
- np.argmin()

#Joining Arrays
Functions Used:
- np.concatenate()
- np.vstack()
- np.hstack()
- np.dstack()

#Splitting Arrays
Functions Used:
- np.split()
- np.hsplit()
- np.vsplit()

#Broadcasting


In [ ]:
arr = np.array([1,2,3])

arr + 5

array([6, 7, 8])